### ISSUE TITLE
Laser images renders all 3 shots as one

### ISSUE THREAD

**Issue by mtn** [gamkedo-la/omega-transmission#4]
The laser shot should alternate between the 3 parts of the loaded image. Currently, the full image is shown. 🎮

**Comment by sahilharidas** [comment]
That was a mistake, sorry.

**Comment by sahilharidas** [comment]
Oops!

**Comment by mtn** [comment]
Resolved in #6

**Comment by mtn** [comment]
jk wrong issue 🥇

**Comment by mtn** [comment]
Leaving as is. The shot is already distinct from others in the game. :zap:
